# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 12:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='body',
            new_name='body_left',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='body_right',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
