# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0002_standardpage_swf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='swf_file',
        ),
    ]
