# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0003_remove_standardpage_swf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='external_link',
            field=models.TextField(blank=True, help_text='Add an external link'),
        ),
    ]
